name: motiontag_sdk_example
description: Demonstrates how to use the Flutter MOTIONTAG SDK Plugin.
version: 1.0.0
homepage: https://github.com/MOTIONTAG/motiontag-sdk-flutter#readme
repository: https://github.com/MOTIONTAG/motiontag-sdk-flutter
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  motiontag_sdk:
    # When depending on this package from a real application you should use:
    #   motiontag_sdk: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  cupertino_icons: ^1.0.5
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^2.0.1
  test: ^1.21.4

flutter:
  uses-material-design: true
