name: motiontag # TODO: Rename it
description: Flutter wrapper for the MOTIONTAG SDK
version: 1.0.0+1
homepage: https://github.com/MOTIONTAG/motiontag-sdk-flutter#readme
repository: https://github.com/MOTIONTAG/motiontag-sdk-flutter

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
# TODO: Update?
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^2.0.1
  test: ^1.21.4

flutter:
  plugin:
    platforms:
      android:
        package: de.motiontag.fluttertracker
        pluginClass: MotionTagPlugin # TODO: Rename it
      ios:
        pluginClass: MotionTagPlugin # TODO: Rename it
