name: motiontag_sdk
description: The Flutter MOTIONTAG SDK It allows embedding the MOTIONTAG detection intelligence into Flutter mobile application.
version: 0.1.4
homepage: https://motion-tag.com/developers
repository: https://github.com/MOTIONTAG/motiontag-sdk-flutter

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^2.0.1
  test: ^1.21.4

flutter:
  plugin:
    platforms:
      android:
        package: de.motiontag.fluttertracker
        pluginClass: MotionTagPlugin
      ios:
        pluginClass: MotionTagPlugin
