# Build, lint and test all targets

trigger:
  branches:
    include:
      - main
pr:
  autoCancel: true
  branches:
    include:
      - '*'

variables:
  - template: templates/common-variables.yml

stages:
  - stage: MainStage
    pool:
      vmImage: ${{variables.vmImage}}
    jobs:
      - job: Lint_And_Test
        timeoutInMinutes: 45
        steps:

          - template: templates/prepare-machine.yml

          # TODO: Remove it
          - script: |
              flutter --help
            displayName: 'flutter Help'

          - task: FlutterCommand@0
            displayName: 'Check code format'
            inputs:
              arguments: 'format --set-exit-if-changed .'
              projectDirectory: '.'

          - task: FlutterCommand@0
            displayName: 'Analyze code'
            inputs:
              arguments: 'analyze'
              projectDirectory: '.'

          - task: FlutterCommand@0
            displayName: 'Unit tests'
            inputs:
              arguments: 'test --coverage'
              projectDirectory: '.'

          - script: |
              brew install lcov
            displayName: 'Install lcov'

          - script: |
              genhtml coverage/lcov.info -o coverage/html
            displayName: 'Parse test coverage'

          - task: PublishPipelineArtifact@1
            displayName: 'Publish test coverage'
            inputs:
              targetPath: $(System.DefaultWorkingDirectory)/coverage/html
              artifactName: PluginTestCoverage

          - task: FlutterCommand@0
            displayName: 'Build Android app'
            inputs:
              arguments: 'build apk --debug'
              projectDirectory: 'example'

          - bash: '$(System.DefaultWorkingDirectory)/pipelines/scripts/init-android-emulator.sh'
            displayName: 'Init Emulator'

          - task: FlutterCommand@0
            displayName: 'Install Android app'
            inputs:
              arguments: 'install'
              projectDirectory: 'example'

          - script: |
              brew tap mobile-dev-inc/tap 
              brew install maestro
            displayName: 'Install Maestro'

          - script: |
              maestro test pipelines/maestro/android-test-flow.yml
            displayName: 'Android integration tests'
