# Build, lint and test all targets

trigger:
  branches:
    include:
      - main
pr:
  autoCancel: false
  branches:
    include:
      - '*'

variables:
  - template: templates/common-variables.yml

stages:
  - stage: MainStage
    pool:
      vmImage: ${{variables.vmImage}}
    jobs:
      - job: Lint_And_Test
        timeoutInMinutes: 90
        steps:

          - template: templates/prepare-machine.yml

          - script: |
              dart format --output=none --set-exit-if-changed .
              displayName: 'Verify formatting'

          - task: FlutterCommand@0
            displayName: 'Analyze code'
            inputs:
              arguments: 'analyze'
              projectDirectory: '.'

          - task: FlutterCommand@0
            displayName: 'Unit tests'
            inputs:
              arguments: 'test --coverage'
              projectDirectory: '.'

          - script: |
              brew install lcov
            displayName: 'Install lcov'

          - script: |
              genhtml coverage/lcov.info -o coverage/html
            displayName: 'Parse test coverage'

          - task: PublishPipelineArtifact@1
            displayName: 'Publish test coverage'
            inputs:
              targetPath: $(System.DefaultWorkingDirectory)/coverage/html
              artifactName: PluginTestCoverage

          - task: FlutterCommand@0
            displayName: 'Build app'
            inputs:
              arguments: 'build apk --debug'
              projectDirectory: 'example'
