# Build, lint and test all targets

trigger:
  branches:
    include:
      - main
pr:
  autoCancel: true
  branches:
    include:
      - '*'

variables:
  - template: templates/common-variables.yml

stages:
  - stage: MainStage
    pool:
      vmImage: ${{variables.vmImage}}
    jobs:
      - job: Lint_And_Test
        timeoutInMinutes: 30
        steps:

          - template: templates/prepare-machine.yml

          - task: FlutterCommand@0
            displayName: 'Format code'
            inputs:
              arguments: 'format --set-exit-if-changed .'
              projectDirectory: '.'

          - task: FlutterCommand@0
            displayName: 'Analyze code'
            inputs:
              arguments: 'analyze'
              projectDirectory: '.'

          - task: FlutterCommand@0
            displayName: 'Test plugin'
            inputs:
              arguments: 'test --coverage'
              projectDirectory: '.'

          - task: FlutterCommand@0
            displayName: 'Test example app'
            inputs:
              arguments: 'test --coverage'
              projectDirectory: 'example'

          - task: FlutterCommand@0
            displayName: 'Build example app'
            inputs:
              arguments: 'build appbundle'
              projectDirectory: 'example'

          - script: |
              genhtml coverage/lcov.info -o coverage/html
            displayName: 'Prepare plugin test coverage'

          - task: PublishPipelineArtifact@1
            displayName: 'Publish plugin test coverage'
            inputs:
              targetPath: $(System.DefaultWorkingDirectory)/coverage/html
              artifactName: PluginTestCoverage
