# Build, lint and test all targets

trigger:
  branches:
    include:
      - main
pr:
  autoCancel: true
  branches:
    include:
      - '*'

variables:
  - template: templates/common-variables.yml

stages:
  - stage: MainStage
    pool:
      vmImage: ${{variables.vmImage}}
    jobs:
      - job: Lint_And_Test
        timeoutInMinutes: 60
        steps:

          - template: templates/prepare-machine.yml

          - task: FlutterCommand@0
            displayName: 'Format code'
            inputs:
              arguments: 'format --set-exit-if-changed .'
              projectDirectory: '.'

          - task: FlutterCommand@0
            displayName: 'Analyze code'
            inputs:
              arguments: 'analyze'
              projectDirectory: '.'

          - task: FlutterCommand@0
            displayName: 'Test plugin'
            inputs:
              arguments: 'test --coverage'
              projectDirectory: '.'

          - task: FlutterCommand@0
            displayName: 'Test example'
            inputs:
              arguments: 'test --coverage'
              projectDirectory: 'example'
